typography_spectrum: 0.18246910674497485
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6875
  lightness: 0.18107884819619358
  saturation: 0.5625
  rhythmicContrast: 0.2261328655295074
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.67619
analytics:
  google: null
  facebook: null
  twitter: null
name: State of the Media
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'State of the Media:'
description: 'All things art and entertainment in Film, Games, Literature et al'
purpose: []
