name: State of the Media
favicon: null
layout_spectrum: 0.022366464138031006
typography_spectrum: 0.18246910674497485
title: 'All things art and entertainment in: Film, Games, Literature, et al'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8428855284582824
  lightness: 0.18107884819619358
  saturation: 0.03306791977956891
  rhythmicContrast: 0.2261328655295074
purpose: []
